language: node_js
node_js:
- node

cache:
  directories:
  - "node_modules"

install:
- sudo apt-get update
- npm install -g @angular/cli
- npm install

script:
- ng build --prod
- npx angular-cli-ghpages --dir=dist/phpconf2019 --cname=2019.phpconf.asia --name="Huiren Woo" --email=giantcrabby@gmail.com --no-silent
